### ISSUE TITLE
[Feature] Handle autoscaling/v2 API version for `HorizontalPodAutoscaler`

### ISSUE THREAD

**Issue by shafeeqes** [gardener/hvpa-controller#104]
**Feature (What you would like to be added):**
Add handling for different API versions of `HorizontalPodAutoscaler`

**Motivation (Why is this needed?):**
The autoscaling/v2beta1 API version of HorizontalPodAutoscaler will no longer be served in v1.25.
We have to migrate manifests and API clients to use the autoscaling/v2 API version, available since v1.23.
Ref: [kubernetes announcement](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125)

**Approach/Hint to the implement solution (optional):**

**Comment by voelzmo** [comment]
Given that we won't use 1.25 for our Seeds until mid next year (EOL for 1.24 is `2023-07-28`), we think that we rather invest time into removing HVPA instead of updating/maintaining it. I'm closing this for now as a 'won't fix' – we can still re-open if we see that HVPA will stick around for longer than we currently think.

**Comment by voelzmo** [comment]
re-opening this: we might not make it in time with HVPA removal for the deprecation of k8s 1.24 in August. So we will need to pick this back up to avoid any pressure when time comes to update our Seeds to 1.25.
